// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("@rescript/std/lib/js/js_dict.js");
var Process = require("process");

function environmentToString(environment) {
  switch (environment) {
    case /* QA */0 :
        return "qa";
    case /* Staging */1 :
        return "stage";
    case /* Production */2 :
        return "prod";
    
  }
}

function stringToEnvironment(str) {
  switch (str) {
    case "prod" :
        return /* Production */2;
    case "dev" :
    case "qa" :
        return /* QA */0;
    case "staging" :
        return /* Staging */1;
    default:
      return ;
  }
}

function getEnvironment(param) {
  var envString = Js_dict.get(Process.env, "NODE_ENV");
  if (envString === undefined) {
    return /* QA */0;
  }
  switch (envString) {
    case "prod" :
        return /* Production */2;
    case "qa" :
        return /* QA */0;
    case "staging" :
        return /* Staging */1;
    default:
      return /* QA */0;
  }
}

exports.environmentToString = environmentToString;
exports.stringToEnvironment = stringToEnvironment;
exports.getEnvironment = getEnvironment;
/* process Not a pure module */
