// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("rescript-test/src/Test.js");

function intEqual(message, a, b) {
  return Test.assertion(message, "intEqual", (function (a, b) {
                return a === b;
              }), a, b);
}

function stringEqual(message, a, b) {
  return Test.assertion(message, "stringEqual", (function (a, b) {
                return a === b;
              }), a, b);
}

function booleanEqual(message, a, b) {
  return Test.assertion(message, "booleanEqual", (function (a, b) {
                return a === b;
              }), a, b);
}

exports.intEqual = intEqual;
exports.stringEqual = stringEqual;
exports.booleanEqual = booleanEqual;
/* Test Not a pure module */
