// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function handler($$event) {
  console.log("auth lambda event:", $$event);
  return Promise.resolve({
              isAuthorized: true
            });
}

exports.handler = handler;
/* No side effect */
