// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jzon = require("rescript-jzon/src/Jzon.js");
var Test = require("rescript-test/src/Test.js");
var Curry = require("@rescript/std/lib/js/curry.js");
var $$Promise = require("@ryyppy/rescript-promise/src/Promise.js");
var Assertions = require("./services/Assertions.js");
var Belt_Array = require("@rescript/std/lib/js/belt_Array.js");
var ListEvents = require("../../src/ListEvents.js");

function stubDynamo(param, param$1, param$2, param$3) {
  return Promise.resolve(Jzon.encodeWith({
                  items: [{
                      eventName: "Test",
                      lastUpdated: 100,
                      permission: /* Free */0,
                      end: 200,
                      primaryKey: "event",
                      start: 100
                    }],
                  lastEvaluatedKey: undefined,
                  ok: true,
                  error: undefined
                }, ListEvents.Codecs.listEventsDynamoResponse));
}

Test.testAsync("should cool async", undefined, (function (cb) {
        var stubEvent = JSON.parse("\n	{\n		\"arguments\": {\n			\"timeRange\": {\n				\"start\": 90,\n				\"end\": 400\n			},\n			\"first\": 1,\n			\"after\": \"\"\n		}\n	}");
        $$Promise.$$catch(ListEvents.listEvents(stubDynamo, stubEvent).then(function (data) {
                  var firstEvent = Belt_Array.get(data.items, 0);
                  if (firstEvent !== undefined) {
                    Assertions.stringEqual(undefined, firstEvent.eventName, "Test");
                    Curry._2(cb, 1, undefined);
                    return Promise.resolve(true);
                  } else {
                    Test.fail("Failed to find a first item", undefined);
                    Curry._2(cb, 1, undefined);
                    return Promise.resolve(false);
                  }
                }), (function (error) {
                console.log("error:", error);
                Test.fail("listEvents exception", undefined);
                Curry._2(cb, 1, undefined);
                return Promise.resolve(false);
              }));
        
      }));

exports.stubDynamo = stubDynamo;
/*  Not a pure module */
