// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jzon = require("rescript-jzon/src/Jzon.js");
var Test = require("rescript-test/src/Test.js");
var Curry = require("@rescript/std/lib/js/curry.js");
var $$Promise = require("@ryyppy/rescript-promise/src/Promise.js");
var Assertions = require("./services/Assertions.js");
var Belt_Array = require("@rescript/std/lib/js/belt_Array.js");
var ListEvents = require("../../src/ListEvents.js");

function stubDynamo(param, param$1, param$2, param$3) {
  return Promise.resolve(Jzon.encodeWith({
                  items: [{
                      eventName: "Test",
                      lastUpdated: 100,
                      permission: /* Free */0,
                      end: 200,
                      primaryKey: "event",
                      start: 100
                    }],
                  lastEvaluatedKey: undefined,
                  hasNextPage: false,
                  ok: true,
                  error: undefined
                }, ListEvents.Codecs.listEventsDynamoResponse));
}

function stubDynamoItems(param) {
  return Promise.resolve(3);
}

Test.testAsync("should list some items", undefined, (function (cb) {
        var stubEvent = JSON.parse("\n	{\n		\"arguments\": {\n			\"timeRange\": {\n				\"start\": 90,\n				\"end\": 400\n			},\n			\"first\": 1,\n			\"after\": \"\"\n		}\n	}");
        $$Promise.$$catch(ListEvents.listEvents(stubDynamo, stubDynamoItems, stubEvent).then(function (json) {
                  var reason = Jzon.decodeWith(json, ListEvents.Codecs.eventsResponse);
                  if (reason.TAG === /* Ok */0) {
                    var firstEvent = Belt_Array.get(reason._0.edges, 0);
                    if (firstEvent !== undefined) {
                      Assertions.stringEqual(undefined, firstEvent.node.name, "Test");
                      Curry._2(cb, 1, undefined);
                      return Promise.resolve(true);
                    } else {
                      Test.fail("Failed to find a first item", undefined);
                      Curry._2(cb, 1, undefined);
                      return Promise.resolve(false);
                    }
                  }
                  console.log("error decoding:", reason._0);
                  Test.fail("Failed decoding", undefined);
                  Curry._2(cb, 1, undefined);
                  return Promise.resolve(false);
                }), (function (error) {
                console.log("error:", error);
                Test.fail("listEvents exception", undefined);
                Curry._2(cb, 1, undefined);
                return Promise.resolve(false);
              }));
        
      }));

Test.testAsync("should get total number of items", undefined, (function (cb) {
        $$Promise.$$catch(ListEvents.getTotalItems(stubDynamoItems).then(function (total) {
                  Assertions.intEqual(undefined, 3, total);
                  Curry._2(cb, 1, undefined);
                  return Promise.resolve(true);
                }), (function (error) {
                console.log("error:", error);
                Test.fail("getTotalItems exception", undefined);
                Curry._2(cb, 1, undefined);
                return Promise.resolve(false);
              }));
        
      }));

exports.stubDynamo = stubDynamo;
exports.stubDynamoItems = stubDynamoItems;
/*  Not a pure module */
